---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mediawiki-opensuse-leap
    image: opensuse:leap
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        httpd_ignore_docker: no
        mysql_ignore_docker: no
scenario:
  name: opensuse-leap
verifier:
  name: goss
  lint:
    name: yamllint
