---
# tasks file for mediawiki
- name: create directory
  file:
    path: "{{ mediawiki_destination }}"
    state: directory

- name: install requirements
  package:
    name: "{{ mediawiki_requirements }}"
    state: present
  register: mediawiki_install_mediawiki
  until: mediawiki_install_mediawiki is succeeded
  retries: 3
  notify:
    - restart httpd

- name: install mediawiki
  unarchive:
    src: "{{ mediawiki_source }}"
    dest: "{{ mediawiki_destination }}"
    remote_src: yes
    creates: "{{ mediawiki_destination }}/mediawiki-{{ mediawiki_version }}"

- name: link mediawiki
  file:
    src: "{{ mediawiki_destination }}/mediawiki-{{ mediawiki_version }}"
    dest: "{{ mediawiki_destination }}/mediawiki"
    state: link
