---
# tasks file for mediawiki
- name: create directory
  file:
    path: "{{ mediawiki_destination[ansible_distribution]
          | default(mediawiki_destination['default']) }}"
    state: directory

- name: install mediawiki
  unarchive:
    src: "{{ mediawiki_source }}"
    dest: "{{ mediawiki_destination[ansible_distribution]
          | default(mediawiki_destination['default']) }}"
    remote_src: yes
    creates: "{{ mediawiki_destination[ansible_distribution]
          | default(mediawiki_destination['default']) }}/mediawiki-{{ mediawiki_version }}"

- name: link mediawiki
  file:
    src: "{{ mediawiki_destination[ansible_distribution]
          | default(mediawiki_destination['default']) }}/mediawiki-{{ mediawiki_version }}"
    dest: "{{ mediawiki_destination[ansible_distribution]
          | default(mediawiki_destination['default']) }}/mediawiki"
    state: link
