---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mediawiki-fedora-latest
    image: fedora:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        httpd_ignore_docker: no
scenario:
  name: fedora-latest
verifier:
  name: goss
  lint:
    name: yamllint
