---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - robertdebock.httpd
    - ansible-role-mediawiki

  tasks:
    - name: test mediawiki installation
      shell: php /var/www/html/mediawiki/index.php && touch done
      args:
        creates: done
