---
- name: Converge
  hosts: all
  gather_facts: false
  become: true

  roles:
    - robertdebock.bootstrap
    - robertdebock.buildtools
    - robertdebock.python_pip
    - robertdebock.httpd
    - ansible-role-mediawiki
