---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: connect to mediawiki
      get_url:
        url: https://localhost/mediawiki
        dest: /tmp/whatever
        validate_certs: no
