---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mediawiki-alpine-latest
    image: alpine:latest
    command: sh -c "while true ; do sleep 1 ; done"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        httpd_ignore_docker: no
scenario:
  name: alpine-latest
verifier:
  name: goss
  lint:
    name: yamllint
