---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    mysql_databases:
      - name: mediawiki

    mysql_users:
      - name: mediawiki
        password: m3d14w1k1
        priv: "mediawiki.*:ALL"

  roles:
    - robertdebock.bootstrap
    - robertdebock.buildtools
    - robertdebock.python_pip
    - robertdebock.httpd
    - robertdebock.php
    - robertdebock.mysql
    - ansible-role-mediawiki
