---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mediawiki-ubuntu-latest
    image: ubuntu:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        httpd_ignore_docker: no
        mysql_ignore_docker: no
scenario:
  name: ubuntu-latest
