---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mediawiki-fedora-rawhide
    image: fedora:rawhide
    registry:
      url: registry.fedoraproject.org
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      mediawiki-fedora-rawhide:
        ansible_python_interpreter: /usr/bin/python3
    group_vars:
      all:
        httpd_ignore_docker: no
        mysql_ignore_docker: no
scenario:
  name: fedora-rawhide
verifier:
  name: goss
  lint:
    name: yamllint
